# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6aa21227362ebf0155107d36133ecb4ec102cef4dfa3b7751246d8152b279a56c5d75f44dadf86246f1da9590a216c29fce51f80a34558ad244c66c90d1de35

test:
  secret_key_base: 815cf8bcab14addf5a5e0ba37e7ed272bd93de666a64c9482ff3003785dd7e1b5163eab1cf2081474db0d21de86ed1459e538c8bc3cbef865e853fee2808b877

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
